<?php

/**
 * Implements hook_theme() to provide a theme for ReviewsListBuilder.
 */
function greyfrut_module2_theme($existing, $type, $theme, $path) {
  return [
    'reviews_list' => [ // Theme hook for the reviews list.
      'variables' => [
        'rows' => [],       // Variable for the rows of the reviews list.
        'attributes' => [], // Variable for additional attributes of the reviews list.
      ],
    ],
  ];
}
